title: // rk // 
email: 
description: Rishi Kaneriya's personal website.
baseurl: 
url: 

highlighter: rouge

paginate: 5
paginate_path: "/blog/page:num/"
permalink: /:categories/:year/:month/:day/:title

markdown: kramdown