title: // rk // 
email: 
description: Rishi Kaneriya's personal website.
baseurl: http://rishikaneriya.com
url: http://rishikaneriya.com

highlighter: rouge

paginate: 5
paginate_path: "/blog/page:num/"
permalink: /:categories/:year/:month/:day/:title

markdown: kramdown